# Classes called from Dart through JNI (lib/native_bindings/andrid_utils.dart,
# generated by jnigen). R8 can't see those calls, so keep them unrenamed.
-keep class com.anandnet.zuno.Equalizer { *; }
-keep class com.anandnet.zuno.SDKInt { *; }
-keep class com.anandnet.zuno.SDKInt$Companion { *; }
